const Database = [
    
    {id: 1, category: "tecnologia", title: "Herobook Pro 14.1", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 349, image: "/images/notebook.jpg", stock: 100},
    {id: 2, category: "tecnologia", title: "Monitor HP", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 150, image: "/images/monitor.jpg", stock: 100},
    {id: 3, category: "tecnologia", title: "Acer Aspire 5", description: "Acer Aspire 5 Computadora portátil delgada, pantalla IPS Full HD de 15.6 pulgadas, AMD Ryzen 3 3200U, gráficos Vega 3, 4GB DDR4, 128GB SSD, teclado retroiluminado, Windows 10 en modo S, A515-43-R19L, plateado", shipping: 163.71, price: 364.99, image: "/images/notebook2.jpg", stock: 100},
    {id: 4, category: "tecnologia", title: "Seagate Disco duro externo", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 62.99, image: "/images/discoduro.jpg", stock: 100},
    {id: 5, category: "tecnologia", title: "Procesador AMD Ryzen 5 3600", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 199.99, image: "/images/procesador.jpg", stock: 100},
    {id: 6, category: "tecnologia", title: "Webcam NexiGo", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 69.99, image: "/images/webcam.jpg", stock: 100},
    {id: 7, category: "tecnologia", title: "Samsung SSD 860 EVO 1TB", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 114.99, image: "/images/discoduro2.jpg", stock: 100},
    {id: 8, category: "tecnologia", title: "Notebook Smart Us", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 359.66, image: "/images/notebook3.jpg", stock: 100},
    {id: 9, category: "moda", title: "Arctix Essential - Pantalones de nieve para hombre", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 42, image: "/images/pantalon.jpg", stock: 100},
    {id: 10, category: "moda", title: "MOERDENG - Chaqueta de esquí para mujer, resistente al agua, abrigo de invierno para nieve, cortavientos de montaña, con capucha", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 69.99, image: "/images/campera.jpg", stock: 100},
    {id: 11, category: "moda", title: "Gildan - Camiseta de algodón de manga larga para hombre, estilo G2400, paquete de 2 unidades.", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 19.53, image: "/images/camisetaalgodon.jpg", stock: 100},
    {id: 12, category: "moda", title: "Wrangler Authentics - Camisa de tela polar de manga larga para hombre, gruesa y resistente", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 18.99, image: "/images/camisa.jpg", stock: 100},
    {id: 13, category: "videojuegos", title: "Musou Dual USB Charging Charger Docking Station Stand for Playstation 4 PS4 / PS4 Pro / PS4 Slim Controller", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 11.99, image: "/images/cargador.jpg", stock: 100},
    {id: 14, category: "videojuegos", title: "PlayStation 4", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 398, image: "/images/ps4.jpg", stock: 100},
    {id: 15, category: "videojuegos", title: "Marvel's Spider-Man: Miles Morales Launch Edition - PlayStation 4", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 49.88, image: "/images/spiderman.jpg", stock: 100},
    {id: 16, category: "videojuegos", title: "Auriculares Ear Force Recon", description: "assadjsadhsadlsd jsdsdkasjdksadjsd kasdjsakdjasdksajdksad ksadjasdksjdkasjdaskdjasd", shipping: 7.50, price: 24.95, image: "/images/auriculares.jpg", stock: 100}
];

export default Database; 